version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django-blog-template-web-dev
    expose:
      - 8000
    volumes:
      - .:/usr/src/app/
      - ./venv/:/usr/src/app/venv/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: django-blog-template-db-dev
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"

  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: django-blog-template-nginx-dev
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
